name: CI/CD

on:
    push:
        branches:
        - main
    workflow_dispatch:

jobs:
    build_and_push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Restore dependencies (install Nuget packages)
              run: dotnet restore

            - name: login to GitHub Container Registry
              run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            - name: Docker image
              run: |
                repository_lowercase=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
                docker build -t ghcr.io/${{github.actor}}/${repository_lowercase}:latest .
                docker push ghcr.io/${{github.actor}}/${repository_lowercase}:latest

    deploy:
        runs-on: self-hosted
        needs: build_and_push
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to GitHub Container Registry
              run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            - name: Pull Docker Image
              run: |
                repository_lowercase=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
                docker pull ghcr.io/houbou98-19/${repository_lowercase}:latest

            - name: Run Docker Container
              run: |
                repository_lowercase=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
                docker run -d --name DeckOfWonder -p 80:8080 ghcr.io/houbou98-19/${repository_lowercase}:latest
